version: "3.4"
services:
  rabbitmq-mumbai:
    container_name: rabbitmq-mumbai
    image: "rabbitmq:3-alpine"
    ports:
      - "6672:5672"
    restart: unless-stopped
  heimdalld-mumbai:
    build: &ref_0
      args:
        UPSTREAM_VERSION: v0.2.1-mumbai
      context: ./build/heimdall
      dockerfile: Dockerfile
    volumes:
      - "heimdall-mumbai:/root/.heimdalld"
    ports:
      - "46656:26656"
      - "46657:26657"
    depends_on:
      - rabbitmq-mumbai
    environment:
      - MONIKER=DAPPNodler
      - >-
        SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/heimdall-snapshot-2022-01-17.tar.gz
      - BOOTSTRAP=1
      - "ETH1_RPC_URL=http://fullnode.dappnode:8545"
    restart: unless-stopped
    image: "heimdalld-mumbai.polygon-mumbai.public.dappnode.eth:0.1.5"
  heimdallr-mumbai:
    environment:
      - REST_SERVER=1
      - "ETH1_RPC_URL=http://fullnode.dappnode:8545"
    build: *ref_0
    volumes:
      - "heimdall-mumbai:/root/.heimdalld"
    ports:
      - "2317:1317"
    depends_on:
      - heimdalld-mumbai
    restart: unless-stopped
    image: "heimdallr-mumbai.polygon-mumbai.public.dappnode.eth:0.1.5"
  bor-mumbai:
    build:
      args:
        UPSTREAM_VERSION: v0.2.14
      context: ./build/bor
      dockerfile: Dockerfile
    environment:
      - >-
        SNAPSHOT_URL=https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/bor-fullnode-node-snapshot-2022-01-24.tar.gz
      - BOOTSTRAP=1
    volumes:
      - "bor-mumbai:/datadir"
    ports:
      - "11545:8545"
      - "11546:8546"
      - "50303:30303"
      - "50303:30303/udp"
    depends_on:
      - heimdallr-mumbai
    restart: unless-stopped
    image: "bor-mumbai.polygon-mumbai.public.dappnode.eth:0.1.5"
volumes:
  heimdall-mumbai: {}
  bor-mumbai: {}
